{
    "body": "We seem to be hitting the maximum open filehandle limit during `spack env activate`.\r\n\r\n### Steps to reproduce the issue\r\n\r\n```console\r\n$ spack env activate -d .\r\n```\r\n\r\nInterestingly enough, if I use:\r\n```console\r\n$ spack -d env activate -d .\r\n```\r\nI can avoid the bug.\r\n\r\n### Error Message\r\n\r\n```console\r\n==> Error: filedescriptor out of range in select()\r\n```\r\n\r\n### Information on your system\r\n\r\nBlue Waters, Cray CNL5, Python 2.6.9\r\n\r\n`spack.yaml`:\r\n```yaml\r\nspack:\r\n  specs:\r\n  - 'gdal+python'\r\n  - 'python@3.7:+sqlite3'\r\n  - 'py-flake8'\r\n  - 'py-matplotlib'\r\n  - 'py-numpy'\r\n  - 'py-pandas'\r\n  - 'py-pytest@3.9:'\r\n  - 'py-scikit-learn'\r\n  - 'py-scipy@0.14:'\r\n  - 'py-tables@3.0.0:'\r\n  - 'py-torch@0.4:'\r\n  - 'py-torchvision'\r\n  concretization: together\r\n```\r\n\r\nThis bug seems to be very intermittent and hard to reproduce...",
    "user": "adamjstewart",
    "url": "https://api.github.com/repos/spack/spack/issues/13608",
    "updated_at": "2020-03-03 12:17:52",
    "created_at": "2019-11-05 22:43:36",
    "closed_at": "None",
    "state": "open",
    "title": "Error: filedescriptor out of range in select()",
    "number": 13608,
    "milestone": null,
    "labels": [
        "bug",
        "environments",
        "triage"
    ],
    "id": 518099028,
    "html_url": "https://github.com/spack/spack/issues/13608",
    "assignees": [],
    "comments": 0
}