{
    "body": "### Steps to reproduce the issue\r\n\r\n```console\r\n$ spack install zlib\r\n==> [2021-07-05-19:56:17.685907] Error: Failed to install zlib due to AttributeError: 'NoneType' object has no attribute 'replace'\r\nTraceback (most recent call last):\r\n  File \"./spack/bin/spack\", line 66, in <module>\r\n    sys.exit(spack.main.main())\r\n  File \"/root/spack/lib/spack/spack/main.py\", line 762, in main\r\n    return _invoke_command(command, parser, args, unknown)\r\n  File \"/root/spack/lib/spack/spack/main.py\", line 490, in _invoke_command\r\n    return_val = command(parser, args)\r\n  File \"/root/spack/lib/spack/spack/cmd/install.py\", line 365, in install\r\n    install_specs(args, kwargs, zip(abstract_specs, specs))\r\n  File \"/root/spack/lib/spack/spack/cmd/install.py\", line 207, in install_specs\r\n    builder.install()\r\n  File \"/root/spack/lib/spack/spack/installer.py\", line 1535, in install\r\n    self._install_task(task)\r\n  File \"/root/spack/lib/spack/spack/installer.py\", line 1101, in _install_task\r\n    _install_from_cache(pkg, cache_only, explicit, unsigned,\r\n  File \"/root/spack/lib/spack/spack/installer.py\", line 273, in _install_from_cache\r\n    installed_from_cache = _try_install_from_binary_cache(\r\n  File \"/root/spack/lib/spack/spack/installer.py\", line 394, in _try_install_from_binary_cache\r\n    matches = binary_distribution.get_mirrors_for_spec(\r\n  File \"/root/spack/lib/spack/spack/binary_distribution.py\", line 1396, in get_mirrors_for_spec\r\n    results = try_direct_fetch(spec,\r\n  File \"/root/spack/lib/spack/spack/binary_distribution.py\", line 1336, in try_direct_fetch\r\n    buildcache_fetch_url = url_util.join(\r\n  File \"/root/spack/lib/spack/spack/util/url.py\", line 156, in join\r\n    obj = urllib_parse.urlparse(\r\n  File \"/home/runner/.setup-spack/._view/33gon3ice5endxsdau2xe2yv35p7kz2v/lib/python3.8/urllib/parse.py\", line 376, in urlparse\r\n    splitresult = urlsplit(url, scheme, allow_fragments)\r\n  File \"/home/runner/.setup-spack/._view/33gon3ice5endxsdau2xe2yv35p7kz2v/lib/python3.8/urllib/parse.py\", line 433, in urlsplit\r\n    scheme = _remove_unsafe_bytes_from_url(scheme)\r\n  File \"/home/runner/.setup-spack/._view/33gon3ice5endxsdau2xe2yv35p7kz2v/lib/python3.8/urllib/parse.py\", line 422, in _remove_unsafe_bytes_from_url\r\n    url = url.replace(b, \"\")\r\nAttributeError: 'NoneType' object has no attribute 'replace'\r\n```\r\n\r\n## Information on your system\r\n\r\n* **Spack:** 0.16.2\r\n* **Python:** 3.8.11\r\n* **Platform:** linux-ubuntu18.04-zen2\r\n\r\n### Additional information\r\n\r\n- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform\r\n- [x] I have searched the issues of this repo and believe this is not a duplicate\r\n- [x] I have run the failing commands in debug mode and reported the output\r\n",
    "user": "haampie",
    "url": "https://api.github.com/repos/spack/spack/issues/24716",
    "updated_at": "2021-09-16 15:22:12",
    "created_at": "2021-07-05 19:58:32",
    "closed_at": "2021-09-16 15:22:11",
    "state": "closed",
    "title": "Spack v0.16.2 can't download using Python 3.8.11 ",
    "number": 24716,
    "milestone": null,
    "labels": [
        "bug",
        "impact-high"
    ],
    "id": 937334078,
    "html_url": "https://github.com/spack/spack/issues/24716",
    "assignees": [],
    "comments": 2
}