{
    "body": "```\r\n==> Building boost [Package]\r\n==> Executing phase: 'install'\r\n==> Error: TypeError: descriptor '__repr__' requires a 'str' object but received a 'syaml_int'\r\n\r\n/spack/repos/builtin/packages/boost/package.py:448, in install:\r\n        445            jobs = 64\r\n        446\r\n        447        b2_options = [\r\n  >>    448            '-j', '%s' % jobs,\r\n        449            '--user-config=%s' % os.path.join(\r\n        450                self.stage.source_path, 'user-config.jam')\r\n        451        ]\r\n```\r\n\r\n### Steps to reproduce the issue\r\n\r\n```console\r\n$ spack install boost@1.70.0\r\n```\r\n\r\nalthough I build the whole `environment` with `python@3:`\r\n```\r\n$python --version\r\nPython 3.8.0\r\n```\r\nbuilt by Spack.\r\n\r\n### Platform and user environment\r\n\r\nPlease report your OS here:\r\n```commandline\r\n$ lsb_release -d\r\nDescription:\tCentOS Linux release 7.6.1810 (Core)\r\n``` \r\n\r\n### Additional information\r\n\r\nSeems that this has to do with Python3 environment, using `spack env activate -V blabla` helps to workaround the issue.",
    "user": "davydden",
    "url": "https://api.github.com/repos/spack/spack/issues/13355",
    "updated_at": "2019-10-29 20:51:49",
    "created_at": "2019-10-21 09:32:27",
    "closed_at": "2019-10-29 20:51:49",
    "state": "closed",
    "title": "Installation issue: boost + python 3 build error",
    "number": 13355,
    "milestone": null,
    "labels": [
        "build-error"
    ],
    "id": 509844435,
    "html_url": "https://github.com/spack/spack/issues/13355",
    "assignees": [
        "scheibelp"
    ],
    "comments": 1
}