{
    "body": "### Steps to reproduce the issue\n\nAfter installing `vtk@9.0.3+python`, the python vtk module is not found in the path:\r\n```\r\n$ spack install vtk@9.0.3+python\r\n$ spack load vtk@9.0.3+python\r\n$ python\r\n>>> import vtk\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\nModuleNotFoundError: No module named 'vtk'\r\n```\n\n### Information on your system\n\n* **Spack:** 0.16.3-4507-32b5669e8d\r\n* **Python:** 3.8.11\r\n* **Platform:** linux-fedora32-haswell\r\n* **Concretizer:** clingo\n\n### Additional information\n\nA similar problem was resolved in #17126 but seem to have reappeared again.\r\n\r\n```\r\n$ spack cd -i vtk@9.0.3\r\n$ ls lib/python3.8/site-packages  # empty\r\n$ ls lib64/python3.8/site-packages \r\nmpi4py/  vtkmodules/  vtk.py\r\n```\r\n```\r\n$ spack load vtk@9.0.3 \r\n$ echo $PYTHONPATH\r\n$spack/opt/spack/linux-fedora32-haswell/gcc-10.3.1/py-mpi4py-3.0.3-fvdbmna4xa3viokrmzaveq33vy6hh2ef/lib/python3.8/site-packages:$spack/opt/spack/linux-fedora32-haswell/gcc-10.3.1/vtk-9.0.3-5dmwd4bxvlvgv5zrgvfj6plobjsxbw2x/lib/python3.8/site-packages:$spack/opt/spack/linux-fedora32-haswell/gcc-10.3.1/py-mpi4py-3.0.3-fvdbmna4xa3viokrmzaveq33vy6hh2ef/lib/python3.8/site-packages\r\n```\r\n\r\n\r\nTo compare the result to the other issue I tried to install `vtk@8.2.0+python` as well but it failed with the error message\r\n```\r\n1 error found in build log:\r\n     242    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY\r\n     243    -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success\r\n     244    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY\r\n     245    -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success\r\n     246    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR\r\n     247    -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success\r\n  >> 248    CMake Error at $spack/opt/spack/linux-fedora32-haswell/gcc-10.3.1/cmake-3.21.3-76wvmpk75pk7tgz\r\n            njnd7spneulakglkm/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):\r\n     249      Could NOT find HDF5 (missing: HDF5_HL_LIBRARIES)\r\n     250    Call Stack (most recent call first):\r\n     251      $spack/opt/spack/linux-fedora32-haswell/gcc-10.3.1/cmake-3.21.3-76wvmpk75pk7tgznjnd7spneulak\r\n            glkm/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)\r\n     252      $spack/opt/spack/linux-fedora32-haswell/gcc-10.3.1/cmake-3.21.3-76wvmpk75pk7tgznjnd7spneulak\r\n            glkm/share/cmake-3.21/Modules/FindHDF5.cmake:1001 (find_package_handle_standard_args)\r\n     253      CMake/FindHDF5.cmake:9 (include)\r\n     254      CMake/vtkModuleMacros.cmake:891 (find_package)\r\n```\r\nIf I should open a additional issue for the second problem, let me know.\r\n\r\n@chuckatkins @danlipsa \r\n@adamjstewart\n\n### General information\n\n- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform\n- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers\n- [X] I have uploaded the build log and environment files\n- [X] I have searched the issues of this repo and believe this is not a duplicate",
    "user": "manuelakuhn",
    "url": "https://api.github.com/repos/spack/spack/issues/26314",
    "updated_at": "2021-10-01 00:52:10",
    "created_at": "2021-09-28 20:53:19",
    "closed_at": "2021-10-01 00:52:10",
    "state": "closed",
    "title": "Installation issue: vtk@9.0.3+python",
    "number": 26314,
    "milestone": null,
    "labels": [
        "build-error"
    ],
    "id": 1010198280,
    "html_url": "https://github.com/spack/spack/issues/26314",
    "assignees": [],
    "comments": 4
}