{
    "body": "We are [experiencing errors on Travis](https://travis-ci.org/LLNL/spack/builds/238234076) due to dependencies:\r\n```console\r\n...\r\n Traceback (most recent call last):\r\n    File \"<string>\", line 1, in <module>\r\n    File \"/tmp/pip-build-F5vHeJ/configparser/setup.py\", line 63, in <module>\r\n      'Topic :: Software Development :: Libraries :: Python Modules',\r\n    File \"/opt/python/2.7.9/lib/python2.7/distutils/core.py\", line 151, in setup\r\n      dist.run_commands()\r\n    File \"/opt/python/2.7.9/lib/python2.7/distutils/dist.py\", line 953, in run_commands\r\n      self.run_command(cmd)\r\n    File \"/opt/python/2.7.9/lib/python2.7/distutils/dist.py\", line 972, in run_command\r\n      cmd_obj.run()\r\n    File \"/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/wheel/bdist_wheel.py\", line 211, in run\r\n      self.run_command('install')\r\n    File \"/opt/python/2.7.9/lib/python2.7/distutils/cmd.py\", line 326, in run_command\r\n      self.distribution.run_command(command)\r\n    File \"/opt/python/2.7.9/lib/python2.7/distutils/dist.py\", line 972, in run_command\r\n      cmd_obj.run()\r\n    File \"/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/setuptools/command/install.py\", line 61, in run\r\n      return orig.install.run(self)\r\n    File \"/opt/python/2.7.9/lib/python2.7/distutils/command/install.py\", line 575, in run\r\n      self.run_command(cmd_name)\r\n    File \"/opt/python/2.7.9/lib/python2.7/distutils/cmd.py\", line 326, in run_command\r\n      self.distribution.run_command(command)\r\n    File \"/opt/python/2.7.9/lib/python2.7/distutils/dist.py\", line 972, in run_command\r\n      cmd_obj.run()\r\n    File \"/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/setuptools/command/install_scripts.py\", line 17, in run\r\n      import setuptools.command.easy_install as ei\r\n    File \"/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/setuptools/command/easy_install.py\", line 49, in <module>\r\n      from setuptools.py27compat import rmtree_safe\r\n    File \"/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/setuptools/py27compat.py\", line 7, in <module>\r\n      import six\r\n  ImportError: No module named six\r\n```\r\n\r\nI hope this will fix things.",
    "user": "alalazo",
    "url": "https://api.github.com/repos/spack/spack/issues/4415",
    "updated_at": "2017-06-01 14:36:36",
    "created_at": "2017-06-01 12:17:00",
    "closed_at": "2017-06-01 12:42:34",
    "state": "closed",
    "title": "travis: fixes failure on six",
    "number": 4415,
    "milestone": null,
    "labels": [
        "tests"
    ],
    "id": 232859962,
    "html_url": "https://github.com/spack/spack/pull/4415",
    "assignees": [],
    "comments": 3
}